"""Shim for backward compat — canonical is morphology_engine.py (KMAX 24)."""
from .morphology_engine import (  # noqa: F401
    A_REF,
    HAS_NUMPY,
    I_REF,
    KMAX,
    P_REF,
    R_MAX,
    R_MIN,
    bake_physical_traits,
    bake_traits_for_index,
    batch_compute_traits,
    compute_asymmetry_index,
    compute_min_vertex_angle,
    compute_moment_of_inertia,
    compute_perimeter,
    compute_polygon_vertices,
    compute_shoelace_area,
    sat_overlap,
)

# Legacy aliases
__all__ = [
    "KMAX",
    "R_MIN",
    "R_MAX",
    "A_REF",
    "P_REF",
    "I_REF",
    "compute_polygon_vertices",
    "compute_shoelace_area",
    "compute_perimeter",
    "compute_moment_of_inertia",
    "compute_min_vertex_angle",
    "compute_asymmetry_index",
    "batch_compute_traits",
    "bake_physical_traits",
    "bake_traits_for_index",
    "sat_overlap",
    "HAS_NUMPY",
]
